#!/bin/sh
set -e

DIR="${1:-src}"
REPORT="cppcheck.txt"

INCLUDES="\
-I/usr/include/SDL2 \
-I/usr/include/cairo \
-I/usr/include/freetype2 \
-I/usr/include/libpng16 \
-I/usr/include/harfbuzz"

cppcheck \
  --enable=warning,performance,unusedFunction,nullPointer \
  --inline-suppr \
  --suppress=missingIncludeSystem \
  --force \
  --quiet \
  --no-color \
  --output-file="$REPORT" \
  $INCLUDES \
  "$DIR"

echo "✅ Rapport : $REPORT"
echo "🔍 Cherche : 'nullPointerOutOfMemory', 'unusedFunction', 'memleak'"
